units:
  kx: 17
  ky: 17
  casepadding: 1.5
points:
  zones:
    matrix:
      anchor.shift: [100, 75]
      rotate: 270
      key:
        spread: 1kx
        padding: 1ky
      columns:
        num:
          rows:
            one.shift: [0kx, 0.25ky]
            five.shift: [0kx, 0.25ky]
            nine.shift: [0kx, 0.25ky]
            backspace:
              shift: [0kx, 0.25ky]
            special.skip: true
        top:
          key.spread: 1.25kx
          rows:
            escape:
              height: 1.5ky
              shift: [0kx, 0.25ky]
            one.shift: [0kx, 0.25ky]
            backspace:
              height: 1.5ky
              shift: [0kx, 0.25ky]
            special.shift: [0kx, 0.5ky]
        home:
          rows:
            escape:
              height: 1.75ky
              shift: [0kx, 0.375ky]
            one.shift: [0kx, 0.375ky]
            equals.skip: true
            backspace:
              height: 2.25ky
              shift: [0kx, -0.375ky]
            special.shift: [0kx, 0.875ky]
        bottom:
          rows:
            escape:
              height: 2.25ky
              shift: [0kx, 0.625ky]
            one.shift: [0kx, 0.625ky]
            dash.skip: true
            equals:
              height: 1.75ky
              shift: [0kx, -0.625ky]
            backspace.shift: [0.125kx, 0.5ky]
            special.shift: [-0.1250kx, 0.125ky]
        mod:
          rows:
            escape:
              height: 1.25ky
              shift: [0kx, 0.125ky]
            one.shift: [0kx, 0.125ky]
            three:               
              height: 1.25ky
              shift: [0kx, 0.125ky]
            four:
              height: 3ky
              shift: [0kx, 1.125ky]
            five.skip: true
            six.skip: true
            seven.skip: true
            eight:
              height: 3kx
              shift: [0kx, -1ky]
            nine:
              height: 1.25ky
              shift: [0kx, 1.125ky]
            zero:
              height: 1.25ky
              shift: [0kx, 0.25ky]
            dash.skip: true
            equals.shift: [0.125kx, -0.75ky]
      rows:
        escape:
        one:
        two:
        three:
        four:
        five:
        six:
        seven:
        eight:
        nine:
        zero:
        dash:
        equals:
        backspace:
        special:
outlines:
  raw:
    - what: rectangle
      where: true
      size: [15.5, 15.5]
      fillet: 0.5
  border:
    - what: polygon
      points:
        - ref: matrix_num_escape
          shift: [-0.5kx-casepadding, -0.5ky-casepadding]
        - ref: matrix_num_backspace
          shift: [-0.5kx-casepadding, 0.5ky+1.25ky+casepadding]
        - ref: matrix_mod_special
          shift: [0.5kx+casepadding, 0.125ky+0.5ky+casepadding]
        - ref: matrix_mod_equals
          shift: [0.5kx+casepadding, -0.1875ky-0.5ky+casepadding]
        - ref: matrix_mod_equals
          shift: [0.5kx-0.125kx+casepadding, -0.1875ky-0.5ky+casepadding]
        - ref: matrix_mod_escape
          shift: [0.5kx+casepadding, -0.125ky-0.5ky-casepadding]
      fillet: 1
pcbs:
  crimes:
    outlines:
      main:
        outline: border
    footprints:
    # Hotswap Choc keys.
    - what: choc
      where: true
      params:
        keycaps: true
        reverse: false
        hotswap: true
        from: "{{column_net}}"
        to: "{{colrow}}"
      adjust:
        rotate: 90
        shift: [0, 0]
    # Through Hole or SMD Diodes
    - what: diode
      where: true
      params:
        from: "{{colrow}}"
        to: "{{row_net}}"
      adjust:
        rotate: 90
        shift: [5, 0]